### ISSUE TITLE
Include Dreambooth models

### ISSUE THREAD

**Issue by Interpause** [Cyberes/stable-diffusion-models#1]
I noticed your guide doesn't mention dreambooth models. There are some organizations on huggingface already hosting dreambooth-finetuned models, so it might be good to mention them.

Also, there have been some deriatives of Waifu Diffusion, but they are NSFW so I am not sure if you want to include them.

**Comment by Cyberes** [comment]
Good idea. Looks like there's an organization that's organized them in one convenient location.

https://huggingface.co/sd-dreambooth-library

I'll copy the textual inversion library auto-update webpage over for sd-dreambooth-library.

And I'm not doing NSFW because it seems everybody is training their own model on their fetishes which is getting ridiculous.

**Comment by Cyberes** [comment]
https://cyberes.github.io/stable-diffusion-dreambooth-library/
